### ISSUE TITLE
Target PublishPackages is broken by the newest version of Fable.React

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-react#82] opened 2018-03-28 16:41 UTC
I don't undertand why but running `./build.sh PublishPackages` result in an error now.

```shell
➜  fable-react git:(master) ✗ ./build.sh PublishPackages
Performance:
 - Runtime: 496 milliseconds
﻿Building project with version: LocalBuild
Shortened DependencyGraph for Target PublishPackages:
<== PublishPackages
   <== Bootstrap

The running order is:
  - Bootstrap
  - PublishPackages
Running build with 1 worker
Starting Target: Bootstrap
Deleting contents of /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/bin
Deleting contents of /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/bin
Deleting contents of /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.Recharts/bin
Deleting contents of /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.Recharts.Sample/bin
Deleting contents of /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/obj
Deleting contents of /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/obj
Deleting contents of /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.Recharts/obj
Deleting contents of /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.Recharts.Sample/obj
dotnet --version
﻿dotnetcli 2.1.4 already installed in PATH
Finished Target: Bootstrap
Starting Target: PublishPackages (==> Bootstrap)
CWD: /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet
dotnet restore
﻿  /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/obj/paket.locked is locked by paket.exe (PID = 86546). Waiting...
  Performance:
   - Disk IO: 17 milliseconds
   - Runtime: 4 seconds
  Performance:
   - Disk IO: 26 milliseconds
   - Runtime: 2 seconds
  Restore completed in 31,11 ms for /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj.
  Restore completed in 30,24 ms for /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/Fable.ReactLeaflet.fsproj.
Deleting contents of /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/temp
CWD: /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet
dotnet pack -c Release -o /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/temp
﻿Microsoft (R) Build Engine version 15.5.180.51428 pour .NET Core
Copyright (C) Microsoft Corporation. Tous droits réservés.

  Restoring packages for /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/Fable.ReactLeaflet.fsproj...
  Restore completed in 29,21 ms for /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj.
  Restore completed in 240,35 ms for /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/Fable.ReactLeaflet.fsproj.
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(786,36): error FS0039: Le champ, le constructeur ou le membre 'GetProperty' n'est pas défini. Peut-être souhaitez-vous l'unedes options suivantes :   GetTypeCode [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(787,13): error FS0072: Recherche d'un objet de type indéterminé basé sur des informations situées avant ce point du programme. Une annotation de type peut être nécessaire avant ce point du programme pour contraindre le type de l'objet. Cela peut permettre la résolution de la recherche. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(788,30): error FS0039: Le champ, le constructeur ou le membre 'GetMethod' n'est pas défini. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(789,13): error FS0072: Recherche d'un objet de type indéterminé basé sur des informations situées avant ce point du programme. Une annotation de type peut être nécessaire avant ce point du programme pour contraindre le type de l'objet. Cela peut permettre la résolution de la recherche. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(789,13): error FS0008: Ce forçage de type ou test de type au moment de l'exécution du type    'a     en     ReactElement    implique un type indéterminé basé sur des informations situées avant ce point du programme. Les tests de types au moment de l'exécution ne sont pas autorisés sur certains types. Des annotations de type supplémentaires sont nécessaires. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(794,26): error FS0039: Le champ, le constructeur ou le membre 'GetProperty' n'est pas défini. Peut-être souhaitez-vous l'unedes options suivantes :   GetTypeCode [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(798,44): error FS0039: Le champ, le constructeur ou le membre 'GetProperties' n'est pas défini. Peut-être souhaitez-vous l'une des options suivantes :   GetRuntimeProperties   get_IsPointer   GetRuntimeProperty [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(800,24): error FS0072: Recherche d'un objet de type indéterminé basé sur des informations situées avant ce point du programme. Une annotation de type peut être nécessaire avant ce point du programme pour contraindre le type de l'objet. Cela peut permettre la résolution de la recherche. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
There's been an error when pushing project: Fable.ReactLeaflet
Please revert the version change in .fsproj
Running build failed.
Error:
System.Exception: '/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet> dotnet pack -c Release -o /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/temp' task failed
  at Microsoft.FSharp.Core.PrintfModule+PrintFormatToStringThenFail@1379[TResult].Invoke (System.String message) [0x00001] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.PrintfImpl+StringPrintfEnv`1[TResult].Finalize () [0x00012] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.PrintfImpl+Final3@247[TState,TResidue,TResult,A,B,C].Invoke (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] env, A a, B b, C c) [0x0007d] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3301-2[T2,T3,T4,TResult,T1].Invoke (T2 u, T3 v, T4 w) [0x00001] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3266-1[T2,T3,TResult,T1].Invoke (T2 u, T3 v) [0x00001] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3253[T2,TResult,T1].Invoke (T2 u) [0x00001] in <5893d081904cf4daa745038381d09358>:0
  at FSI_0005.Fable.FakeHelpers+run@62-2.Invoke (System.String arg30) [0x00001] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0001f] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V,W] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2, V arg3) [0x0003d] in <5893d081904cf4daa745038381d09358>:0
  at FSI_0005.Fable.FakeHelpers.run (System.String workingDir, System.String fileName, System.String args) [0x000f8] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at FSI_0005.Fable.FakeHelpers.pushNuget (System.String dotnetExePath, Fake.ReleaseNotesHelper+ReleaseNotes releaseNotes, Microsoft.FSharp.Core.FSharpOption`1[T] build, System.String projFile) [0x001a2] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at FSI_0005.Fable.FakeHelpers.publishPackages2 (System.String baseDir, System.String dotnetExePath, Microsoft.FSharp.Collections.FSharpList`1[T] packages) [0x000e7] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at FSI_0005.Fable.FakeHelpers.publishPackages (System.String baseDir, System.String dotnetExePath, Microsoft.FSharp.Collections.FSharpList`1[T] packages) [0x00017] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at FSI_0005.Build+clo@34-2.Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00010] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <59b649fdccf1c534a7450383fd49b659>:0
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x0004b] in <59b649fdccf1c534a7450383fd49b659>:0

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target            Duration
------            --------
Bootstrap         00:00:00.2029209
PublishPackages   Failure
Total:            00:00:21.5487564
---------------------------------------------------------------------
Status:           Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: '/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet> dotnet pack -c Release -o /Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.ReactLeaflet/temp' task failed
  at Microsoft.FSharp.Core.PrintfModule+PrintFormatToStringThenFail@1379[TResult].Invoke (System.String message) [0x00001] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.PrintfImpl+StringPrintfEnv`1[TResult].Finalize () [0x00012] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.PrintfImpl+Final3@247[TState,TResidue,TResult,A,B,C].Invoke (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] env, A a, B b, C c) [0x0007d] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3301-2[T2,T3,T4,TResult,T1].Invoke (T2 u, T3 v, T4 w) [0x00001] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3266-1[T2,T3,TResult,T1].Invoke (T2 u, T3 v) [0x00001] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.OptimizedClosures+Invoke@3253[T2,TResult,T1].Invoke (T2 u) [0x00001] in <5893d081904cf4daa745038381d09358>:0
  at FSI_0005.Fable.FakeHelpers+run@62-2.Invoke (System.String arg30) [0x00001] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2) [0x0001f] in <5893d081904cf4daa745038381d09358>:0
  at Microsoft.FSharp.Core.FSharpFunc`2[T,TResult].InvokeFast[V,W] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] func, T arg1, TResult arg2, V arg3) [0x0003d] in <5893d081904cf4daa745038381d09358>:0
  at FSI_0005.Fable.FakeHelpers.run (System.String workingDir, System.String fileName, System.String args) [0x000f8] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at FSI_0005.Fable.FakeHelpers.pushNuget (System.String dotnetExePath, Fake.ReleaseNotesHelper+ReleaseNotes releaseNotes, Microsoft.FSharp.Core.FSharpOption`1[T] build, System.String projFile) [0x001a2] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at FSI_0005.Fable.FakeHelpers.publishPackages2 (System.String baseDir, System.String dotnetExePath, Microsoft.FSharp.Collections.FSharpList`1[T] packages) [0x000e7] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at FSI_0005.Fable.FakeHelpers.publishPackages (System.String baseDir, System.String dotnetExePath, Microsoft.FSharp.Collections.FSharpList`1[T] packages) [0x00017] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at FSI_0005.Build+clo@34-2.Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00010] in <c594ec5c06b84fcd8da875ac6c3d30c1>:0
  at Fake.TargetHelper+targetFromTemplate@209-1[a].Invoke (Microsoft.FSharp.Core.Unit unitVar0) [0x00001] in <59b649fdccf1c534a7450383fd49b659>:0
  at Fake.TargetHelper.runSingleTarget (Fake.TargetHelper+TargetTemplate`1[a] target) [0x0004b] in <59b649fdccf1c534a7450383fd49b659>:0
```

**Comment by alfonsogarciacaro** [comment] 2018-03-30 10:34
Hmm, one of the errors happens because of these lines (for server rendering):

https://github.com/fable-compiler/fable-react/blob/4dec6b9e4b4e2895efc1fd1cde2053724ab1e426/src/Fable.React/Fable.Helpers.React.fs#L784-L786

It can be fixed by making all packages in the repo target `netstandard2.0`. It shouldn't be an issue but I wonder why it worked before, any idea @zaaack?

**Comment by zaaack** [comment] 2018-04-02 10:47
@alfonsogarciacaro Do you have full error trace? I cannot reproduce this with the master branch.

**Comment by alfonsogarciacaro** [comment] 2018-04-02 14:37
@zaaack Yes, Maxime posted it on his first comment. The relevant part is:

```
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(786,36): error FS0039: Le champ, le constructeur ou le membre 'GetProperty' n'est pas défini. Peut-être souhaitez-vous l'unedes options suivantes :   GetTypeCode [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(787,13): error FS0072: Recherche d'un objet de type indéterminé basé sur des informations situées avant ce point du programme. Une annotation de type peut être nécessaire avant ce point du programme pour contraindre le type de l'objet. Cela peut permettre la résolution de la recherche. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(788,30): error FS0039: Le champ, le constructeur ou le membre 'GetMethod' n'est pas défini. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(789,13): error FS0072: Recherche d'un objet de type indéterminé basé sur des informations situées avant ce point du programme. Une annotation de type peut être nécessaire avant ce point du programme pour contraindre le type de l'objet. Cela peut permettre la résolution de la recherche. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(789,13): error FS0008: Ce forçage de type ou test de type au moment de l'exécution du type    'a     en     ReactElement    implique un type indéterminé basé sur des informations situées avant ce point du programme. Les tests de types au moment de l'exécution ne sont pas autorisés sur certains types. Des annotations de type supplémentaires sont nécessaires. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(794,26): error FS0039: Le champ, le constructeur ou le membre 'GetProperty' n'est pas défini. Peut-être souhaitez-vous l'unedes options suivantes :   GetTypeCode [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(798,44): error FS0039: Le champ, le constructeur ou le membre 'GetProperties' n'est pas défini. Peut-être souhaitez-vous l'une des options suivantes :   GetRuntimeProperties   get_IsPointer   GetRuntimeProperty [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.Helpers.React.fs(800,24): error FS0072: Recherche d'un objet de type indéterminé basé sur des informations situées avant ce point du programme. Une annotation de type peut être nécessaire avant ce point du programme pour contraindre le type de l'objet. Cela peut permettre la résolution de la recherche. [/Users/mangelmaxime/Workspace/Github/fable-compiler/fable-react/src/Fable.React/Fable.React.fsproj]
```

It's failing because `GetProperty` is not a member of `Type`. This is because MSFT originally wanted to cut down on reflection capabilities when doing `GetType` (I think it was for native compilation) and force you to use `GetTypeInfo`, but they added the API back in netstandard2.0. I don't know how I managed to publish the package before, maybe it depends on the dotnet SDK version used? /shrug

**Comment by zaaack** [comment] 2018-04-03 03:03
@alfonsogarciacaro After running `dotnet build` in `Fable.React`, I can see the error messages now, not sure why they didn't appear before. I just create a pr to fix this. https://github.com/fable-compiler/fable-react/pull/83

**Closed** 2018-04-03 07:11 UTC
Labels: bug
